### ISSUE TITLE
Cleanups before upstreaming to sorbet/sorbet

### ISSUE THREAD

**Issue by st0012** [Shopify/sorbet#279]
```[tasklist]
### Tasks
- [ ] Remove changes under `.vscode/`
- [ ] Remove `Gemfile` and `Gemfile.lock` (that were added to make `RubyLSP: Show sytnax tree` work)
- [ ] Remove things added in #311
- [ ] Document `--parser=prism` CLI flag
- [ ] See if we can add the parser flag to sorbet.run
```

**Comment by amomchilov** [comment]
Done. This original Prism work was merged upstream in https://github.com/sorbet/sorbet/pull/8485
