### ISSUE TITLE
Parser tests with valid Ruby code that failed by Prism translation

### ISSUE THREAD

**Issue by st0012** [Shopify/sorbet#327]
```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/sorbet/issues/338
- [ ] https://github.com/Shopify/sorbet/issues/332
- [ ] https://github.com/Shopify/sorbet/issues/336
- [ ] https://github.com/Shopify/sorbet/issues/337
- [ ] https://github.com/Shopify/sorbet/issues/331
- [ ] https://github.com/Shopify/sorbet/issues/330
- [ ] https://github.com/Shopify/sorbet/issues/328
```
