### ISSUE TITLE
Corpus tests that probably fail due to parse tree differences

### ISSUE THREAD

**Issue by st0012** [Shopify/sorbet#382]
```[tasklist]
### Tasks
- [ ] //test:test_PosTests/testdata/cfg/examples_prism                         
- [ ] //test:test_PosTests/testdata/deviations/keyword_method_names_prism      
- [ ] //test:test_PosTests/testdata/local_vars/z_super_args_splats_blocks_prism 
- [ ] //test:test_PosTests/testdata/lsp/completion/bad_arguments_prism         
- [ ] //test:test_PosTests/testdata/lsp/completion/bad_list_elems_prism        
- [ ] //test:test_PosTests/testdata/lsp/completion/case_1_prism                
- [ ] //test:test_PosTests/testdata/lsp/completion/case_2_prism                
- [ ] //test:test_PosTests/testdata/lsp/completion/eof_prism                   
- [ ] //test:test_PosTests/testdata/lsp/completion/missing_fun_prism           
- [ ] //test:test_PosTests/testdata/namer/arguments_prism                  
```

**Comment by st0012** [comment]
It turned out all the remaining items were error recovery related. So after removing them, we have essentially completed this issue 😂
